[project]
name = "ml-ex"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "folium>=0.20.0",
    "geopandas>=1.1.4",
    "joblib>=1.5.3",
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pydeck>=0.9.1",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "streamlit>=1.62.0",
    "xgboost>=3.4.1",
]

[dependency-groups]
dev = [
    "ipykernel<7",
]
